### PR TITLE
Add `then` method to ExtendedPromiseInterface

### PR DESCRIPTION
**Pull request by psafarov**
Fixes return type for `then` method in ExtendedPromiseInterface

### CODE REVIEW

**Comment by WyriHaximus** [comment]
To be perfectly honest I'm not sure what has to be fixed here since `ExtendedPromiseInterface` extends from `PromiseInterface` and that already has the return type declared in the docblock

**Comment by WyriHaximus** [comment]
To be perfectly honest I'm not sure what has to be fixed here since `ExtendedPromiseInterface` extends from `PromiseInterface` and that already has the return type declared in the docblock

**Comment by psafarov** [comment]
The problem is, the return type of `PromiseInterface::then` is `PromiseInterface`. Maybe this snippet will be more explanatory:
```php
function test(ExtendedPromiseInterface $promise) {
    $promise2 = $promise->then(...);
    // oops, static type check tells us that `otherwise` method is undefined,
    // as $promise2 is an instance of `PromiseInterface`
    $promise2->otherwise(...); 
}
```
In this example I assigned result of `then` to a variable, but same problem occurs when we have a chain of methods:
```php
function test(ExtendedPromiseInterface $promise) {
    // neither `otherwise` nor `done` are recognized during static type check
    $promise->then(...)->otherwise(...)->done(...); 
}
```

**Comment by WyriHaximus** [comment]
Ah yes that makes sense, wouldnt't changing the return type to `self` on `PromiseInterface` do the same with a less invasive change?

**Comment by psafarov** [comment]
That was the first thing I did. Unfortunately it didn't fix the problem for PhpStorm, so I went with this solution. It will be understandable if this PR will be rejected, but at least `PromiseInterface` should be changed for `self`, in my opinion.

**Comment by WyriHaximus** [comment]
> if this PR will be rejected

In it's current state yes, but I rather focus on finding a solution first and preferably update this PR :smile: . Let me have a look at it as well

**Comment by psafarov** [comment]
PR is updated. `PromiseInterface::then` doc follows phpdoc standard now. It doesn't fix incorrect type hinting in PhpStorm though, but I don't see what can be done here.

**Comment by clue** [comment]
@psafarov Thanks for reporting, that's an interesting issue and I can see where you're coming from! :+1: 

That being said, while I do agree that the current type definition is *inaccurate*, I'm not sure this is something we can address in a minor release without a BC break. The updated type definition is technically a BC break that consumers of this package could possibly miss when using custom implementations of said interfaces.

This has been addressed via #75 for the upcoming v3.0 release, so we may as well document this as a known limitation for the current version. What do you think? :+1:

**Comment by psafarov** [comment]
@clue isn't `self` more open than `PromiseInterface` in this case? Just not sure what BC we are talking about, but if it is true, then off course it would make perfect sense to delay this PR.

**Comment by clue** [comment]
@psafarov It's my understanding `self` will not use [late static binding](https://www.php.net/manual/en/language.oop5.late-static-bindings.php), i.e. it references the exact class name it's defined in. In other words, `self` and `PromiseInterface` should be equivalent in this case.

**Comment by psafarov** [comment]
I see, that means my change doesn't help in any way. And using `static` means breaking BC. I am closing this PR then. Thanks for explanation.

**Pull request closed without merging**
