### PR TITLE
Use \Throwable exclusively in rejection function docs

### PR DESCRIPTION
**Pull request by jsor**
Follow-up for #138.

### CODE REVIEW

**Comment by jsor** [comment]
Good point, i will try to rework the docs 👍 . But we must make sure to **not** recommend `\Exception` as type-declarations in callbacks. Used eg. in `otherwise()` callbacks, this might lead to uncaught `\Error`'s.

**Comment by clue** [comment]
I concur, adding `Throwable` as the type hint and adding explicit docs for `Exception` seems to be the best solution here :+1:

**Comment by WyriHaximus** [comment]
@clue added a short paragraph about `Throwable` vs `Exception`.

**Comment by WyriHaximus** [comment]
:tada: !

**Pull request merged**
