### PR TITLE
Cancellation of promise collections

### LINKED ISSUE #33: Cancellation of promise collections
What is the recommended way to cancel promise collections?

This library provides several promise collection primitives, which all have valid use cases.

One might assume the following is the way to go:

```php
$promises = array(
    accessSomeRemoteResource(),
    accessSomeRemoteResource(),
    accessSomeRemoteResource()
);

$promise = \React\Promise\all($promises);

// what does this do?
$promise->cancel();
```

How does this cope with cancellation support?

This is currently not implemented, i.e. calling `cancel()` currently has *no* effect.

Should we consider adding this?

Also, if yes, how could cancellation support work for the other primitives?

### PR DESCRIPTION
**Pull request by jsor**
Allow cancellation of promises returned by functions working on promise collections.

Closes #33

### CODE REVIEW

**Comment by jsor** [comment]
ping for review @cboden @clue @WyriHaximus
Also, should this go in 2.3 or 3.0?

**Comment by WyriHaximus** [comment]
LGTM, 2.3 :+1: (unless I missed something there isn't any BC break so 2.3 seems more appropriate then 3.0)

**Comment by jsor** [comment]
I'm planning to add this to 3.0.

**Comment by clue** [comment]
Changes LGTM :+1: Personally, I would tend towards getting this into v2.3 first and then subsequently into v3.0

**Pull request merged**
