### PR TITLE
Support foreign thenables in resolve()

### LINKED ISSUE #45: Support foreign thenables in resolve()
Allow foreign promises to be turned into trusted promises by checking `method_exists($promiseOrValue, 'then')`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve

### PR DESCRIPTION
**Pull request by jsor**
Closes #45

### CODE REVIEW

**Comment by clue** [comment]
LGTM :+1:

**Comment by WyriHaximus** [comment]
LGTM :shipit:

**Comment by jsor** [comment]
Released in [v2.4.0](https://github.com/reactphp/promise/releases/tag/v2.4.0).

**Comment by joshdifabio** [comment]
Fantastic!

**Pull request merged**
